package com.invoiceautomationservice.domain.model;

public enum AuditAction {
  COMPANY_CREATED,
  CUSTOMER_CREATED,
  ISSUER_TAX_PROFILE_CONFIGURED,
  DOCUMENT_SERIES_CONFIGURED,
  DRAFT_CREATED,
  DRAFT_UPDATED,
  DRAFT_APPROVED,
  DRAFT_CANCELLED,
  DOCUMENT_ISSUED,
  DOCUMENT_RETRIED,
  DOCUMENT_STATUS_REFRESHED,
  CREDIT_NOTE_ISSUED,
  DEBIT_NOTE_ISSUED,
  DOCUMENT_CANCELLED
}
