package com.invoiceautomationservice.domain.model;

public enum AuditAction {
  TENANT_ONBOARDED,
  COMPANY_CREATED,
  CUSTOMER_CREATED,
  ISSUER_TAX_PROFILE_CONFIGURED,
  DOCUMENT_SERIES_CONFIGURED,
  COMPANY_MEMBER_ADDED,
  COMPANY_MEMBER_UPDATED,
  COMPANY_MEMBER_REMOVED,
  DRAFT_CREATED,
  DRAFT_UPDATED,
  DRAFT_APPROVED,
  DRAFT_CANCELLED,
  DOCUMENT_ISSUED,
  DOCUMENT_RETRIED,
  DOCUMENT_STATUS_REFRESHED,
  CREDIT_NOTE_ISSUED,
  DEBIT_NOTE_ISSUED,
  DOCUMENT_CANCELLED,
  CONVERSATION_CREATED,
  MESSAGE_ADDED,
  CONVERSATION_CLOSED,
  CONVERSATION_PROCESSED
}
