spring:
  application:
    name: invoice-automation-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:invoice_automation_service}
    username: ${DB_USER:invoice_user}
    password: ${DB_PASSWORD:invoice_password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
management:
  endpoints:
    web:
      exposure:
        include: health,info
